name: Python Tests with Tox

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.11']

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y openbabel autodock autodock-vina

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox poetry

      - name: Run tests with tox
        run: |
          tox -e py
